version: "3.7"
services:
  score-calculator-db:
    image: postgres:12
    container_name: reviews
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reviews
    volumes:
      - ./schema-postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
